import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Jura } from "next/font/google";
import { NavbarDock } from "@/components/generalUi/navbarDock";



export const jura = Jura({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col content-center max-w-3xl px-4 mx-auto mt-10 ${jura.className}bg-gray-200 dark:bg-black
          
          `}
      >
        {children}
        <div className={`fixed bottom-4 w-full left-0`}>
          <NavbarDock />
        </div>
      </body>
    </html>
  );
}
