import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/generalUi/navbar";
import { Inter } from 'next/font/google'
import { NavbarDock } from "@/components/generalUi/navbarDock";



const inter = Inter({ subsets: ['latin'] })

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col content-center w-[700px] max-w-[80%] mx-auto mt-10 ${inter.className}bg-gray-200 dark:bg-black`}
      >
        {children}
        {/* <Navbar /> */}
        <NavbarDock />
      </body>
    </html>
  );
}
