import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col content-center max-w-3xl px-4 mx-auto mt-10 ${GeistSans.variable}
            ${GeistMono.variable}
          bg-gray-200 dark:bg-[#111010] 
          mb-12
          `}
      >
        <div className={`flex gap-4 mb-8 text-xl  justify-end cursor-pointer`}>
          <Link href={"/"}>Home</Link>
          <Link href={"/blog"}>Blog</Link>
        </div>
        {children}

      </body>
    </html>
  );
}
